inherits = "gruvbox"

"punctuation" = { fg = "orange1", modifiers = ["bold"] }
"operator" = { fg = "purple1", modifiers = ["bold"] } # Logical (&&, ||) and - I assume - Mathematical (+, %) operators

"warning" = { fg = "yellow1", bg = "bg1" }
"error" = { fg = "red1", bg = "bg1" }
"info" = { fg = "aqua1", bg = "bg1" }
"hint" = { fg = "blue1", bg = "bg1" }

"ui.bufferline.active" = { underline = { color = "orange1", style = "line"} } 

"ui.selection" = { fg = "bg0", bg = "yellow0" }
# "ui.selection" = { bg = "bg3", modifiers = ["reversed"] }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "fg2", modifiers = ["reversed"] }

"diagnostic.warning" = { underline = { color = "yellow1", style = "curl" } }
