inherits = "noctis"

'ui.cursor' = { fg = "dark-green", bg = "white" } # Fallback cursor colour, non-primary cursors when there are multiple (shift-c).
'ui.cursor.primary' = { fg = "dark-green", bg = "light-blue" } # The primary cursor when there are multiple (shift-c).
'ui.cursor.insert' = { fg = "dark-green", bg = "light-blue" } # The cursor in insert mode (i).
'ui.cursor.select' = { fg = "dark-green", bg = "light-blue" } # The cursor in select mode (v).
'ui.cursor.match' = { fg = "dark-green", bg = "red", modifiers = ["bold"] } # The matching parentheses of that under the cursor.

'property' = { fg = "red" } # Regex group names.

'ui.virtual.whitespace' = { fg = "light-gray" }
'ui.virtual.indent-guide' = { fg = "light-gray" } # Indentation guides.

[palette]
light-gray = "#354e51"
