theme = "current-theme"

[editor]
line-number = "absolute"
idle-timeout = 100
completion-trigger-len = 2
scrolloff = 5  # default 5
color-modes = true
cursorline = true
cursorcolumn = true
bufferline = "always"
rulers = [80]
popup-border = "popup"
insert-final-newline = false
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "separator", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "position", "position-percentage", "file-encoding", "file-type"]

[editor.lsp]
display-messages = true
display-inlay-hints = false
goto-reference-include-declaration = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
# select = "underline"

[editor.file-picker]
hidden = false      # enables ignoring hidden files
git-ignore = true   # don't show up in files in filepicker (.gitignore file) when hidden=true
ignore = true       # don't show up in files in filepicker (.ignore file) when hidden=true
max-depth = 10
follow-symlinks = true
deduplicate-links = false

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
# character = "┆"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint" # error, warning, info, hint
other-lines = "disable"

[keys.normal]
";" = "remove_primary_selection"
"ret" = ["open_below", "normal_mode"]
# "C-o" = "jump_forward"
# "C-i" = "jump_backward"
"A-," = ["goto_next_diag", ":yank-diagnostic", ":vsplit-new", "paste_clipboard_after"]

[keys.normal.space]
W = ":write"
q = ":quit"
Q = ":quit!"
c = ":buffer-close"
C = ":buffer-close!"
[keys.normal.space.space]
"r" = ":lsp-restart"
"s" = ":lsp-stop"
# relative path (takes cwd of helix, but when using <g-f> to open file, takes cwd as the current opened file directory)
# ls -1 $(pwd)
"f" = [":pipe find $(pwd) -maxdepth 1 | tail -n +2", "toggle_comments"]
B = ":sh bash /Users/roger/.config/helix/hx-git-blame.sh %{buffer_name} %{cursor_line}" # Show blame information
U = ":sh bash /Users/roger/.config/helix/hx-git-blame.sh --url-only %{cursor_line} %{buffer_name} | xargs -I{} open {}" # Open PR or commit url in browser# relative path (takes cwd of helix, but when using <g-f> to open file, takes cwd as the current opened file directory)
