[language-server.haskell-language-server.config.haskell]
"formattingProvider" = "fourmolu"  

[language-server.my-omnisharp]
command = "dotnet"
args = ["/Users/roger/.dotnet/omnisharp-osx-arm64-net6.0/OmniSharp.dll", "--languageserver" ]


[[language]]
name = "haskell"
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
auto-format = true
# formatter = { command = "zsh", args = ["-c", "fourmolu -d --stdin-input-file $(pwd)/app/Main.hs" ] }
# formatter = { command = "stylish-haskell", args = [] }

[[language]]
name = "c-sharp"
language-servers = ["my-omnisharp"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }

