[language-server.haskell-language-server.config.haskell]
"formattingProvider" = "fourmolu"
"plugin" = { "stan" = { "globalOn" = true }}

[language-server.purescript-language-server.config.purescript]
"formatter" = "purs-tidy"

[language-server.my-omnisharp]
command = "dotnet"
args = ["/Users/roger/.dotnet/omnisharp-osx-arm64-net6.0/OmniSharp.dll", "--languageserver" ]
 
# [language-server.nil.config.nil.formatting]
# command = ["nixfmt"]

[[language]]
name = "nix"
formatter = { command = 'nixfmt' }
auto-format = false

[[language]]
name = "typst"
formatter = { command = 'typstyle' }
auto-format = false

[[language]]
name = "haskell"
auto-format = false
language-servers = [ "haskell-language-server" ]

[[language]]
name = "c-sharp"
language-servers = ["my-omnisharp"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = false

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = false

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "markdown"
formatter = { command = "prettier" , args = ["--parser", "markdown"] }
