[language-server.haskell-language-server.config.haskell]
"formattingProvider" = "ormolu"  
"plugin" = { "stan" = { "globalOn" = true }}

[language-server.my-omnisharp]
command = "dotnet"
args = ["/Users/roger/.dotnet/omnisharp-osx-arm64-net6.0/OmniSharp.dll", "--languageserver" ]
 
[[language]]
name = "haskell"
auto-format = false
language-servers = [ "haskell-language-server" ]

[[language]]
name = "c-sharp"
language-servers = ["my-omnisharp"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
auto-format = false

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = false

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false
