[[language]]
name = "haskell"
roots = ["Setup.hs", "stack.yaml", "*.cabal"]

[[language]]
name = "c-sharp"
language-server = { command = "dotnet", args = ["/Users/roger/.dotnet/omnisharp-osx-arm64-net6.0/OmniSharp.dll", "--languageserver" ] }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
# language-server = { command = "OmniSharp" }

# contents of "$HOME/.dotnet/tools/OmniSharp" 
#!/bin/zsh
# dotnet "/Users/roger/.dotnet/omnisharp-osx-arm64-net6.0/OmniSharp.dll" --languageserver


